CREATE TABLE IF NOT EXISTS hospitals (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    hospital_id UUID REFERENCES hospitals(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


ALTER TABLE patients ADD COLUMN hospital_id UUID REFERENCES hospitals(id) ON DELETE SET NULL;
ALTER TABLE doctors ADD COLUMN hospital_id UUID REFERENCES hospitals(id) ON DELETE SET NULL;
ALTER TABLE patients ADD COLUMN user_id UUID REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE doctors ADD COLUMN user_id UUID REFERENCES users(id) ON DELETE CASCADE;